name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate Dockerfile
        id: generate
        run: ./gen.sh
      - name: Commit files
        run: |
          git config --local user.email "yasuyuki.ymd@gmail.com"
          git config --local user.name "Yasuyuki YAMADA"
          git commit -a -m "[auto] Generate Dockerfile" || echo "no changes"
          git tag -f -a ${tag_name} -m "${tag_name} Tagged by CI"
        env:
          tag_name: ${{ steps.generate.outputs.version }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
      - name: Build and push the docker image to ghcr.io
        run: |
          echo $CR_PAT | docker login ghcr.io -u yasuyuky --password-stdin
          docker build . -t ghcr.io/yasuyuky/rust-ubuntu:latest -t ghcr.io/yasuyuky/rust-ubuntu:$TAGNAME
          docker push -a ghcr.io/yasuyuky/rust-ubuntu
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          TAGNAME: ${{ steps.generate.outputs.version }}
